# syntax=docker/dockerfile:1

FROM golang:1.19-alpine

WORKDIR /app

RUN apk add chromium
RUN apk add ffmpeg

RUN mkdir bin
RUN mkdir tmp

COPY go.mod ./
COPY go.sum ./

ADD internal internal
ADD cmd cmd

RUN go mod download

RUN cd cmd/poller && go build -o ../../bin/poller

CMD [ "./bin/poller" ]