# syntax=docker/dockerfile:1

FROM golang:1.23-alpine

WORKDIR /app

RUN echo "https://dl-cdn.alpinelinux.org/alpine/v3.18/main" >> /etc/apk/repositories && \ 
    echo "https://dl-cdn.alpinelinux.org/alpine/v3.18/community" >> /etc/apk/repositories

RUN apk update
RUN apk add chromium
RUN apk add ffmpeg

RUN mkdir bin
RUN mkdir tmp

COPY go.mod .
COPY go.sum .
COPY internal internal
COPY cmd cmd

RUN go mod download
RUN cd cmd/scraper && go build -o ../../bin/scraper

CMD [ "./bin/scraper" ]