CREATE TABLE IF NOT EXISTS players(
  id INT PRIMARY KEY,
  name VARCHAR(500) NOT NULL,
  first_name VARCHAR(500) NOT NULL,
  last_name VARCHAR(500) NOT NULL,
  age INT NOT NULL,
  nationality VARCHAR(500) NOT NULL,
  height VARCHAR(500) NOT NULL,
  weight VARCHAR(500) NOT NULL,
  photo VARCHAR(500) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
