CREATE TABLE IF NOT EXISTS teams(
  id INT PRIMARY KEY,
  name VARCHAR(500) UNIQUE,
  code VARCHAR(500) NOT NULL,
  country VARCHAR(500) NOT NULL,
  founded INT NOT NULL,
  national BOOLEAN NOT NULL,
  logo VARCHAR(500) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);