name: Deploy

on:
  push:
    branches: ["master"]

jobs:
  poller:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.poller
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/top90-poller

      - name: Pull image on ec2
        run: |
          mkdir keys
          touch keys/defaultec2.pem
          echo "${{ secrets.EC2_PRIVATE_SSH_KEY }}" | tr -d '\r' > keys/defaultec2.pem
          chmod 400 keys/defaultec2.pem
          ssh -o StrictHostKeyChecking=no -i keys/defaultec2.pem ec2-user@ec2-35-171-182-157.compute-1.amazonaws.com docker pull ${{ secrets.DOCKERHUB_USERNAME }}/top90-poller
          ssh -o StrictHostKeyChecking=no -i keys/defaultec2.pem ec2-user@ec2-35-171-182-157.compute-1.amazonaws.com docker image prune -f

  api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/top90

      - name: Pull latest image
        run: |
          mkdir keys
          touch keys/defaultec2.pem
          echo "${{ secrets.EC2_PRIVATE_SSH_KEY }}" | tr -d '\r' > keys/defaultec2.pem
          touch .env
          echo "${{ secrets.TOP90_ENV_FILE_PROD }}" | tr -d '\r' > .env
          chmod 400 keys/defaultec2.pem
          ssh -o StrictHostKeyChecking=no -i keys/defaultec2.pem ec2-user@ec2-54-197-209-45.compute-1.amazonaws.com docker pull ${{ secrets.DOCKERHUB_USERNAME }}/top90
        
      - name: Restart API
        run: |
          ssh -o StrictHostKeyChecking=no -i keys/defaultec2.pem ec2-user@ec2-54-197-209-45.compute-1.amazonaws.com docker stop top90-server || true
          ssh -o StrictHostKeyChecking=no -i keys/defaultec2.pem ec2-user@ec2-54-197-209-45.compute-1.amazonaws.com docker container prune -f
          ssh -o StrictHostKeyChecking=no -i keys/defaultec2.pem ec2-user@ec2-54-197-209-45.compute-1.amazonaws.com docker run --env-file .env -p 7171:7171 -d --restart unless-stopped --name top90-server wweitzel/top90
          ssh -o StrictHostKeyChecking=no -i keys/defaultec2.pem ec2-user@ec2-54-197-209-45.compute-1.amazonaws.com docker image prune -f
